# -*- coding: utf-8 -*-
"""Metodos_Predictivos_TP_2026_estructurado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11g4bJCmGlEHG240W6fQpYMEufJE8h2V_

#### Trabajo Práctico · 2.er Cuatrimestre 2026

### METODOS PREDICTIVOS PARA LA GESTION

#### Tecnicatura Universitaria en Gestión y Análisis de Datos - FCE UBA

--------------------------------------------------------------------------

### 0. DESCRIPCIÓN Y FUENTE DEL DATASET

Para el desarrollo del trabajo se seleccionó el dataset Online News Popularity, disponible en el UCI Machine Learning Repository.

La base contiene información sobre artículos publicados por Mashable durante un período de dos años. Cada registro representa un artículo y contiene distintas características asociadas a su contenido y publicación, como la cantidad de palabras del título y del artículo, número de imágenes y videos, cantidad de enlaces, palabras clave, temática, día de publicación y diferentes indicadores relacionados con la subjetividad y el sentimiento del contenido.

El dataset cuenta con 39.797 observaciones y 58 variables predictoras. Además, incluye variables no predictivas y la variable objetivo shares, que representa la cantidad de veces que cada artículo fue compartido en redes sociales.

El objetivo del análisis será estudiar la relación entre las características de los artículos y su popularidad, buscando predecir la cantidad de veces que un artículo será compartido. Debido a que la variable objetivo shares es numérica, el problema será abordado mediante técnicas de regresión.

Fuente: UCI Machine Learning Repository — Online News Popularity.
Autores: Kelwin Fernandes, Pedro Vinagre, Paulo Cortez y Pedro Sernadela.

--------------------------------------------------------------------------

## 1. CARGA Y EXPLORACIÓN INICIAL DEL DATASET

En esta sección se realiza la carga de la base y una primera inspección de su estructura, sin aplicar todavía transformaciones sobre los datos.

### 1.1 Carga de librerías y del dataset
"""

# Importamos la función fetch_ucirepo de la librería ucimlrepo.
# Esta función permite descargar datasets directamente desde
# el repositorio UCI Machine Learning Repository (https://archive.ics.uci.edu/).
!pip install ucimlrepo
from ucimlrepo import fetch_ucirepo
import pandas as pd

# Descargamos el dataset "Online News Popularity".
# El parámetro id=332 identifica de manera única a este dataset dentro del repositorio UCI.
online_news_popularity = fetch_ucirepo(id=332)

# Separamos las variables predictoras (X) de la variable objetivo (y).
# X2 contiene las características de los artículos que utilizaremos como predictoras.
X2 = online_news_popularity.data.features

# y2 contiene la variable objetivo "shares":
# cantidad de veces que un artículo fue compartido.
y2 = online_news_popularity.data.targets

# Mostramos los metadatos generales del dataset.
print(online_news_popularity.metadata)

# Mostramos la información provista por UCI sobre cada variable.
print(online_news_popularity.variables)

"""### 1.2 Dimensiones e identificación de la variable objetivo

"""

# Mostramos los nombres de las variables predictoras
print("Variables predictoras:")
print(X2.columns)

# Mostramos el nombre de la variable objetivo
print("\nVariable objetivo:")
print(y2.columns)

# Mostramos las dimensiones de ambos DataFrames
print("\nDimensiones:")
print("X2:", X2.shape)
print("y2:", y2.shape)

"""### 1.3 Normalización de los nombres de las variables

"""

# Los nombre de las variables poseen espacios a los costados

# Limpiamos los nombres de las variables predictoras
X2.columns = X2.columns.str.strip()

# Limpiamos el nombre de la variable objetivo
y2.columns = y2.columns.str.strip()

"""### 1.4 Construcción del DataFrame completo

"""

# Unimos las variables predictoras (X2) con la variable objetivo (y2)
# para disponer de un DataFrame completo para el análisis exploratorio.
df = pd.concat([X2, y2], axis=1)

"""### 1.5 Inspección inicial de la estructura

"""

# Dimensiones del DataFrame completo: filas y columnas.
df.shape

# Estructura general: nombres de columnas, tipos de datos y valores no nulos.
df.info()

"""### 1.6 Inventario y tipología de variables

Se visualizarán los primeros 10 registros para obtener un panorama general de los campos (las columnas que no caben, se visualizarán por fuera de este informe, pero serán descritas y mostradas por separado posteriormente).
"""

df.head(10)

"""Se clasifican las variable a continuación en distintos grupos conceptuales, para su mejor desarrollo, a los fines de facilitar la definición respecto al significado de cada una."""

#Agrupamiento de los nombres de las variables en listas asociadas correspondientemente a sus grupos conceptuales bajo los cuales clasificamos dichas variables aleatorias.
cols_estr_art = [
    "n_tokens_title",
    "n_tokens_content",
    "n_unique_tokens",
    "n_non_stop_words",
    "n_non_stop_unique_tokens",
    "average_token_length",
    "num_keywords"
]

cols_enlaces_multimedia = [
    "num_hrefs",
    "num_self_hrefs",
    "num_imgs",
    "num_videos"
]

cols_canal_tematico = [
    "data_channel_is_lifestyle",
    "data_channel_is_entertainment",
    "data_channel_is_bus",
    "data_channel_is_socmed",
    "data_channel_is_tech",
    "data_channel_is_world"
]

cols_keywords = [
    "kw_min_min",
    "kw_max_min",
    "kw_avg_min",
    "kw_min_max",
    "kw_max_max",
    "kw_avg_max",
    "kw_min_avg",
    "kw_max_avg",
    "kw_avg_avg"
]

cols_referencias = [
    "self_reference_min_shares",
    "self_reference_max_shares",
    "self_reference_avg_sharess"
]

cols_dia_publicacion = [
    "weekday_is_monday",
    "weekday_is_tuesday",
    "weekday_is_wednesday",
    "weekday_is_thursday",
    "weekday_is_friday",
    "weekday_is_saturday",
    "weekday_is_sunday",
    "is_weekend"
]

cols_lda = [
    "LDA_00",
    "LDA_01",
    "LDA_02",
    "LDA_03",
    "LDA_04"
]

cols_sentimiento_subjetividad = [
    "global_subjectivity",
    "global_sentiment_polarity",
    "global_rate_positive_words",
    "global_rate_negative_words",
    "rate_positive_words",
    "rate_negative_words",
    "avg_positive_polarity",
    "min_positive_polarity",
    "max_positive_polarity",
    "avg_negative_polarity",
    "min_negative_polarity",
    "max_negative_polarity",
    "title_subjectivity",
    "title_sentiment_polarity",
    "abs_title_subjectivity",
    "abs_title_sentiment_polarity"
]

cols_no_predictivas = [
    "url",
    "timedelta"
]

col_objetivo = [
    "shares"
]

"""**Estructura del artículo**"""

df.loc[:,cols_estr_art] #Seleccionamos los atributos correspondientes a variables clasificadas dentro del conjunto de Estructura del Artículo.

"""Variables de estructura del artículo:

* n_tokens_title: cantidad de palabras del título
* n_tokens_content: cantidad de palabras del cuerpo del artículo (qué tan largo es).
* n_unique_tokens: proporción de palabras distintas dentro del artículo con respecto al número de palabras totales. Si se repiten m palabras de las n palabras totales de un artículo, entonces:

  $$
  \text{n_unique_tokens} = \frac{m}{n}\forall m<n \wedge m,n\in \mathbb{N} \implies \text{n_unique_tokens}\in [0;1] \in \mathbb{Z}
  $$
  
  Téngase en cuenta que al considerar el conjunto de los naturales sin el 0 para m y n, garantizamos que no se contemple la división por cero, la cual tampoco tendría sentido en el contexto de este análisis porque un artículo sin palabras no es más que una hoja en blanco.
  Lo interesante de esta variable es que siempre está comprendida en un rango entre 0 y 1 como recién se especificó, permitiendo una comparación entre todas las observaciones del espectro de valores que adopta esta variable en la muestra dada y evitando una correlación innecesaria entre la variable n_tokens_content y una variable que sería m por sí sola (podría llamarse m_non_stop_tokens), justamente porque, a mayor número de palabras totales, podría existir una tendencia a tener mayor número de palabras distintas, lo cual no se puede saber a ciencia cierta tampoco debido a factores tales como la posibilidad de que el autor del artículo tuviera un léxico lo suficientemente amplio, los editores podrían no ser muy cuidadosos, o el público al cual estuviera dirigido el artículo podría requerir de un vocabulario más acotado para lograr conectar con los receptores del mensaje, entre otras causas, incluyendo la aleatoriedad misma, por lo que esta correlación tendría un "enmascaramiento" por superposición de causas posibles ajenas al propio n_tokens_content.
* n_non_stop_words: stop words son palabras muy frecuentes pero que aportan poca información para el análisis del texto, las cuales son conectores y preposiciones como "el", "la", "de", "y", entre otras. Por lo tanto, n_non_stop_words es el número de palabras que **no** son stop words.
* n_non_stop_unique_tokens: dadas las explicaciones anteriores, esta variable es la proporción de palabras que no son stop words y que, además, son únicas. Aplíquese análogamente los conceptos anteriormente desarrollados a la comprensión de la descripción realizada en torno a esta variable.
* average_token_length: longitud promedio de las palabras del artículo. Esto es:
$$
\sum_{i=1}^{L}{\frac{\text{Número de caracteres}_i}{\text{n_tokens_content}}}
$$
Siendo i el índice para indicar "la i-ésima palabra" dentro del artículo considerado de un total de L palabras.
* num_keywords: cantidad de palabras clave asociadas al artículo.


Todas estas variables son cuantitativas.
"""

df.loc[:,cols_enlaces_multimedia] #atributos de enlaces multimedia

"""**Variables de enlaces multimedia**
* num_hrefs: número total de links del artículo.
* num_self_hrefs: cantidad de links internos que apuntan a otros artículos de Mashable (medio que publicó los artículos del dataset).
* num_imgs: número de imágenes
* num_videos: cantidad de videos

Nuevamente, variables cuantitativas.
"""

df.loc[:,cols_canal_tematico] #Atributos canal temático.

"""Temática o canal del artículo:
* data_channel_is_lifestyle:estilo de vida (como en TV, el canal Discovery Home & Health).
* data_channel_is_entertainment: entretenimiento
* data_channel_is_bus: negocios
* data_channel_is_socmed: redes sociales.
* data_channel_is_tech: tecnología
* data_channel_is_world: global

Estas son variables cualitativas que corresponden a una numerización y cuyos atributos "dummy", columnas binarias por cada uno de los valores del atributo original (temática o canal) ya fueron creadas desde la fuente, es decir, estas son variables dummy provenientes del dataframe original y ahorran otro paso.
"""

df.loc[:,cols_keywords] #Atributos asociados a palabras clave

"""Variables asociadas a estimadores muestrales de palabras clave:
Describen qué tan populares son las palabras clave asociadas con el artículo, usando como referencia las veces que otros artículos asociados a esas keywords fueron compartidos.
Es como una forma de medir popularidad por cantidad de veces que se compartieron otros artículos asociados, siendo el vínculo entre ambos establecido a través de las keywords. Es conceptualmente análogo a tener un Hashtag tendencia en una red social, o un trending topic, sólo que asociado a palabras clave.

* kw_min_min: El mínimo de shares asociado a las keywords, tomando el mínimo de cada keyword.
* kw_max_min: El máximo de esos mínimos.
* kw_avg_min: El promedio de esos mínimos.
* kw_min_min: El mínimo de shares asociado a las keywords, tomando el mínimo de cada keyword.
* kw_max_min: El máximo de esos mínimos.
* kw_avg_min: El promedio de esos mínimos.

Aplíquese análogamente a los máximos y promedios de shares históricos de las palabras clave, que están contempladas en las demás variables exhibidas en el dataframe anterior.

Variables cuantitativas.


"""

df.loc[:,cols_dia_publicacion]

"""**Día de la publicación**:

Son variables dummy, una por cada día de la semana, otra numerización ya hecha desde el dataframe crudo original.

Variable cualitativa ya numerizada.
Is weekend indica si es fin de semana o no. Aquí hay que evaluar si no hay correlación entre las 7 variables de día de semana y la octava de fin de semana.
"""

df.loc[:,cols_lda]

"""**LDA: Latent Dirichlet Allocation**:

Es una técnica mediante la cual se infiere de qué temas habla un documento en base a las palabras que contiene, lo cual arroja valores donde cada artículo tiene una asociación comprendida entre 0 y 1 para cada temática. Anteriormente se describieron 6 temáticas, pero en las columnas de LDA sólo hay 5. Esto es algo lógico porque la sumatoria de las puntuaciones de las 6 temáticas tiene que dar 1 como resultado total. Si se utilizaran las 6 variables, claramente la sexta siempre sería linealmente dependiente de las otras 5 (n-1 grados de libertad).

El nivel de asociación de un artículo con una temática no sería en sí mismo cualitativo porque se está haciendo la estimación de un parámetro, por lo que podría ser cuantitativo, y aun así estas variables podrían introducir un componente de aleatoriedad adicional, aunque permiten evaluar qué tan amplio es el abanico de temas que abarca a un artículo, lo cual podría favorecer el abordaje de un público más heterogéneo y, consecuentemente, favorecer su popularidad. Vale la pena tenerlo en cuenta, pero evaluar que no produzca inconvenientes para la regresión.
"""

df.loc[:,cols_sentimiento_subjetividad]

"""Variables de sentimiento y polaridad:
Son cualitativas y describen hacia qué sentimiento tiende el artículo, proporción de palabras positivas y negativas (prestar atención a que ambas suman 1 en el caso del análisis global, pero en el no global se excluyen las no neutrales, lo que evita multicolinealidad) y polaridad (hacia qué sentimiento tienden) las palabras positivas y negativas cuantificando su intensidad.
Aquí tenemos variables cuantitativas.

### 1.7 Análisis de escalas y rangos

Normalización analizada previamente. La estandarización se evaluará en el análisis de outliers para variables cuantitativas.

## 2. LIMPIEZA Y PREPROCESAMIENTO

### 2.1 Valores faltantes
### 2.2 Registros duplicados
### 2.3 Inconsistencias
### 2.4 Variables no informativas
### 2.5 Detección y análisis de outliers
### 2.6 Decisiones de limpieza y justificación

**Sección pendiente de desarrollo.**

### 2.1 Valores faltantes
"""

# Identificación de campos con valores faltantes:

df.isna().sum().sort_values(ascending=False)

"""No hay valores faltantes en ningún campo, por lo que no es necesario realizar imputación de valores de momento. Los demás tratamientos serán evaluados en el análisis de outliers más adelante.

### 2.2 Registros duplicados
"""

print(f"Suma de registros duplicados: {df.duplicated().sum()}") #suma de registros duplicados

"""### 2.3 Inconsistencias"""

#Se aplicará a variables cualitativas
df[cols_canal_tematico].isin([0, 1]).all().all() #Verificamos que las columnas de canal temático sean de 0 y 1, no pueden ser no binarias porque son columnas dummy.

"""El valor anterior es verdadero por lo que todas las columnas de canal temático respetan la regla de numerización."""

cols_dia_publicacion = [
    "weekday_is_monday",
    "weekday_is_tuesday",
    "weekday_is_wednesday",
    "weekday_is_thursday",
    "weekday_is_friday",
    "weekday_is_saturday",
    "weekday_is_sunday"
]

df[cols_dia_publicacion].sum(axis=1).value_counts() #verificamos que cada artículo se corresponda con un día de la semana, no puede haber un artículo en dos días (no es física cuántica, no hay superposición de estados).
#La suma tiene que ser igual al número de registros (39644) para el valor 1 y no tiene que haber ningún otro valor.

"""El dataframe también es consistente en días de publicación."""

#Verificación de sumas de LDA = 1 (Explicado en descripción de campos).
import numpy as np #importamos numpy para operaciones algebraicas y redondeos en este caso.
suma_lda = df[cols_lda].sum(axis=1) #suma de los LDA a lo largo de cada registro.
resultado = pd.Series(np.isclose(suma_lda, 1)) #Vemos cuántos cumplen con la suma de LDA = 1, con tolerancia de redondeo.
resultado.value_counts() #Conteo de los resultados

df.loc[~resultado, cols_lda] #como apareció un resultado inconsistente con esta regla, lo visualizaremos

#seleccionamos el registro completo para verlo mejor
df.loc[~resultado, :]

"""El resultado anterior es de un artículo de entretenimiento.
Resulta extraño que con un número de 1570 palabras, 701 palabras distintas y 650 palabras non-stop, no se haya podido inferir nada con respecto a la temática de este artículo.
Hay que evaluar el impacto que tiene este valor inconsistente en el conjunto. Ya de por sí representa un ínfimo porcentaje con respecto al total por ser un único registro con inconsistencias.
Primero veremos causa posible, y podemos evaluarlo con las columnas que faltan en la visualización anterior del df
"""

df.loc[~resultado,cols_sentimiento_subjetividad]

"""No sólo falló el LDA aquí, sino también la evaluación de subjetividad, polaridad y sentimiento en las palabras. Evaluaremos en cuántos casos pasa esto, pero primero eliminaremos esta fila para no contaminar el resto de las observaciones para el análisis, dado que una fila con valores nulos en variables asociadas a conceptos lingüísticos pudo haber sido causada por una eventualidad en la ejecución de un algoritmo de machine learning o IA. Continuaremos con los siguientes campos del dataframe para distinguir si los nulos en LDA tienen una posible causa común con los nulos en la evaluación de sentimientos y polaridad o si todos los demás campos de este registro tienen nulos también, en cuyo caso podría inferirse un error en la carga de datos."""

df.loc[~resultado,cols_dia_publicacion]

"""Vemos de forma consistente con el análsis de incongruencias en días de publicación que este artículo tiene un valor asignado, un día martes. Ergo, los valores nulos en LDA pueden estar relacionados con los de sentimientos y polaridad, casualmente donde se requiere una cuantificación de atributos lingüísticos y emocionales. El análisis de outliers podrá darnos un mejor panorama para determinar si es conveniente eliminar este registro o no, si hay más registros que deban tratarse y qué valores deben excluirse del análisis posterior, debido a que existe la posibilidad de crear un dataframe que excluya determinados campos o registros, conservando los datos originales de forma tal que, en caso de considerarse en un análisis posterior la necesidad de incluirlos de nuevo o de probar si estos pueden mejorar algún estimador asociado a la calidad y explicabilidad del modelo de regresiór, esto pueda realizarse sin problemas. Una vez más observamos la importancia e influencia de la limpieza y preprocesamiento sobre el resto del trabajo llevado a cabo en el presente documento.

### 2.4 - Variables no informativas

Anteriormente se explicó la importancia de las variables clasificadas, pero no se incluyeron las variables que, acorde a la fuente original de este trabajo (UCI) son no explicativas, las cuales son url (es un link, no aporta nada más que una referencia) y timedelta, que es la cantidad de días entre la publicación del artículo y la adquisición del dataset, lo cual tampoco es relevante para el análisis.

### 2.5 Análisis de Outliers

#### Tipos de outliers:

* Globales: un dato destaca por sí sólo individualmente del resto de los datos en el dataset
* Contextuales: qué tiene sentido que esté presente como dato en sí mismo (no podría tenerse una magnitud ml cuando el campo es torque de un motor). Esto se asocia más a la inconsistencia. De la misma forma sería extraño tener temperaturas en °C en un campo y que un valor sea de 400, en cuyo ejemplo podría ser un error de carga, porque el investigador no se dio cuenta y puso la temperatura en Kelvin.
* Colectivos: Anomalías que en su conjunto destacan sobre el resto de los datos aunque individualmente no necesariamente sean anómalos.

### Número de variables:

Claramente estamos considerando decenas de variables aleatorias, por lo que nos enfrentamos a un problema que debe ser analizado como lo que es: multivariado. De esta forma, salvo que criteriosamente se requiera realizar este análisis posteriormente entre dos variables particulares por alguna causa en específico, los análisis se realizarán con los métodos aplicables a variables cuantitativas con un enfoque multivariable. Esto capturará mejor los outliers en su conjunto teniendo en cuenta todas las variables que entran en juego. Donde se ve claramente esto es en el primer método que se aplicará, explicado a continuación:

### Distancia de Mahalanobis:
Cuánto se aleja cada observación del conjunto de datos de forma global, cuantificado mediante un D^2 que es el cuadrado de una distancia entre la observación (puede pensarse como un punto de n dimensiones, donde cada uno de los datos de cada campo para esta observación es una componente del vector que representa espacialmente su posición). En n dimensiones, el conjunto de puntos del dataset formará una región donde se minimizan las distancias de todos los puntos a uno en particular, calculado, que actuará de centro, como una especie de centro de masa en física, que es un punto donde se minimizan las distancias. La región mencionada es la elipsoide (en dos dimensiones sería una elipse, de 3 en adelante es una elipsoide) y ese "centro de masa" es el centroide. En resumen: a mayor $D^2$, mayor distancia del punto con respecto al conjunto. Esto nos srive para identificar outliers globales.
"""

#Como aplicaremos los 3 métodos, empezando por Mahalanobis, a variables cuantitativas, las aislaremos del resto del df creando uno nuevo sólo con los campos previamente clasificados como cuantitativos.
cols_cuantitativas = cols_estr_art + cols_enlaces_multimedia + cols_keywords + cols_referencias + cols_lda + cols_sentimiento_subjetividad

!pip install scipy
from scipy.spatial.distance import mahalanobis #importación de la librería para Mahalanobis

media = df[cols_cuantitativas].mean().values #valor medio de cada campo.
cov = np.cov(df[cols_cuantitativas].values, rowvar=False) #covarianza de los datos. No requiere estandarización porque Mahalanobis considera escalas.
inv_cov = np.linalg.inv(cov) #matriz inversa de covarianza.
df.insert(0, 'id', np.arange(1, len(df) + 1)) #Se agrega columna de id al dataset.
df['mahalanobis_2'] = [
    mahalanobis(x, media, inv_cov) ** 2
    for x in df[cols_cuantitativas].values
] #Aquí se obtienen los D**2 para las observaciones.

df[['id'] + cols_cuantitativas + ['mahalanobis_2']] \
    .sort_values('mahalanobis_2', ascending=False) \
    .head(50) #Aquí se muestran los primeros 50 registros del cálculo resultante por Mahalanobis

"""Ya con sólo ver esto nos topamos nuevamente con el registro inconsistente donde faltaba el análisis de polaridad y sentimientos y el LDA, al tope de la lista con los 10 valores de mayor distancia al conjunto (según Mahalanobis). Este valor es extremadamente atípico y se puede ver con claridad por su $D^2$ (véase columna mahalanobis_2).
Por otro lado tenemos un segundo artículo en la lista con una distancia de Mahalanobis llamativa. También se observa que la proporción de palabras distintas es inconsistente porque tiene un valor de 750 cuando es una proporción y no un valor absoluto. Esto puede ser un error de carga de datos que pudo haber influenciado en LDA y polaridad. Este registro de por sí está mal y será excluido por completo: se debe asegurar la pureza de la muestra.
"""

df = df[df['id'] != 31038]

"""$\color{red}{\mathbf{\text{Registro id=31038 excluido}}}$

Volvemos a hacer Mahalanobis sin el registro que contaminaba la muestra.
"""

#Pisamos las variables con nuevos valores:
media = df[cols_cuantitativas].mean().values #valor medio de cada campo.
cov = np.cov(df[cols_cuantitativas].values, rowvar=False) #covarianza de los datos. No requiere estandarización porque Mahalanobis considera escalas.
inv_cov = np.linalg.inv(cov) #matriz inversa de covarianza.
df['mahalanobis_2'] = [
    mahalanobis(x, media, inv_cov) ** 2
    for x in df[cols_cuantitativas].values
] #Aquí se obtienen los D**2 para las observaciones.

df[['id'] + cols_cuantitativas + ['mahalanobis_2']] \
    .sort_values('mahalanobis_2', ascending=False) \
    .head(50) #Aquí se muestran los primeros 50 registros del cálculo resultante por Mahalanobis

#No visualizaremos Mahalanobis porque es imposible hacer una representación visual que pueda realmente capturar todas las dimensiones.
#El ser humano ve en 3 dimensiones e intenta simular esas 3 dimensiones en representaciones que terminan siendo 2D en el monitor de una PC.
#En el dataframe tenemos 44 variables cuantitativas explicativas. Imposible.

"""Estamos viendo registros con un $D^2$ muy elevado, y todos tienen algo en común: una proporción de non stop words igual a 1. Es imposible redactar un texto sin utilizar conectores y preposiciones. Estos valores no tienen sentido. Se identificarán todos aquellos donde ocurra esto y veremos su distancia de Mahalanobis al cuadrado."""

df[np.isclose(df['n_non_stop_words'], 1)][['id'] + cols_cuantitativas + ['mahalanobis_2']] \
    .sort_values('mahalanobis_2', ascending=False) #usamos el isclose de numpy para considerar una tolerancia por redondeo de punto flotante.

#la mayor parte de los n_non_stop_words están dando valores cercanos a 1, teniendo un margen de tolerancia con el is close de 5 decimales en este caso.
#vamos a ver qué nos trae el describe para ver qué ocurre con este campo:
df['n_non_stop_words'].describe()

df['n_non_stop_words'].value_counts().sort_index() #Vemos cuántas observaciones dan 0 y cuántas dan cercanas a 1.

pd.set_option('display.precision', 15)
df[['id', 'n_non_stop_words']].sort_values('n_non_stop_words', ascending=False).head(20)

#Lo siguiente que se va a hacer es ver qué tanto aporta este campo al modelo de regresión utilizando la matriz de correlación, incluyendo a la variable objetivo (y sacando a mahalanobis):
cols_corr = (
    cols_cuantitativas
    + cols_canal_tematico
    + cols_dia_publicacion
    + ['shares']
)

matriz_correlacion = df[cols_corr].corr()

matriz_correlacion['shares'].sort_values()

matriz_correlacion['shares'].describe()

"""No se puede eliminar este campo del dataset por lo menos de momento, porque la mayor parte de los campos tienen un nivel de correlación menor o igual al 3,16% y, por si fuera poco, su nivel de correlación no es muy diferente del nivel de correlación que tiene el resto de las variables con respecto a shares del artículo porque la mayor parte tiene un nivel de correlación inferior al 3%."""

df.loc[df['n_non_stop_words'] == 0,
       ['id', 'n_tokens_content', 'n_non_stop_words', 'n_non_stop_unique_tokens']] #Acá vemos que los registros con valores que son prácticamente 0 son artículos en los cuales no hay palabras registradas.

df.loc[df['n_tokens_content'] == 0, cols_estr_art].describe().T #Vamos a ver qué pasa con estos casos

"""Hay 1181 registros en los que n_tokens_content toma el valor 0. En estos registros, las variables derivadas del contenido (n_unique_tokens, n_non_stop_words, n_non_stop_unique_tokens y average_token_length) también toman valor 0. Sin embargo, los registros conservan información correspondiente al título y a las keywords. Esto indica que se trata de artículos con información de título y metadatos, pero sin contenido textual registrado.

"""

#Podemos probar de quitar los registros con valores nulos y volver a intentar de hacer la matriz de correlación.
df_sin_0_nnstopw = df[df['n_non_stop_words'] != 0]

cols_corr = cols_cuantitativas + ['shares']

matriz_correlacion = df_sin_0_nnstopw[cols_corr].corr()

matriz_correlacion['shares']

#Comparamos la diferencia entre tener o no tener las filas donde n_non_stop_words=0
comparacion = pd.concat([
    df[cols_corr].corr()['shares'].rename('con_ceros'),
    df_sin_0_nnstopw[cols_corr].corr()['shares'].rename('sin_ceros')
], axis=1)

comparacion['diferencia'] = comparacion['sin_ceros'] - comparacion['con_ceros']

comparacion.sort_values('diferencia')

#No se aprecian cambios radicales en la elminación de estos registros, pero los campos que no son cero aportan información y afectan la matriz de correlación en general, por lo que no sería correcto eliminarlos a priori.

#Ahora veremos qué ocurre si quitamos n_non_stop_words de los campos, pero no quitamos los registros con valores 0 en n_non_stop_words.
# Matriz original: todos los registros + n_non_stop_words
cols_corr = (
    cols_cuantitativas
    + cols_canal_tematico
    + cols_dia_publicacion
    + ['shares']
)

matriz_con_nnonstop = df[cols_corr].corr()


# Matriz sin n_non_stop_words: mismos registros, misma variable objetivo
cols_corr_sin_nnonstop = [
    col for col in cols_corr
    if col != 'n_non_stop_words'
]

matriz_sin_nnonstop = df[cols_corr_sin_nnonstop].corr()

#Comparación:
comparacion = pd.DataFrame({
    'con_n_non_stop_words': matriz_con_nnonstop['shares'].drop('shares'),
    'sin_n_non_stop_words': matriz_sin_nnonstop['shares'].drop('shares')
})

comparacion['diferencia'] = (
    comparacion['sin_n_non_stop_words']
    - comparacion['con_n_non_stop_words']
)

comparacion.sort_values(
    'diferencia',
    key=abs,
    ascending=False
)

"""Se evaluó la eliminación de la variable n_non_stop_words mediante la matriz de correlación de Pearson. La variable presentó una correlación lineal muy débil con la variable objetivo shares (r = -0,0196). Al recalcular la matriz excluyendo dicha variable, manteniendo la totalidad de los registros, no se observaron modificaciones en las correlaciones entre las restantes variables predictoras y shares.
De todas formas esto no es suficiente para determinar si se puede eliminar o no, por lo que se conservará este campo y no se eliminarán los registros, a menos que se realice otro hallazgo luego.

### Local Outlier Factor

LOF compara la densidad local de una observación con la de sus vecinos.

Un valor cercano a 1 indica un comportamiento parecido al de sus vecinos. Valores mayores indican mayor grado de anomalía.

Se aplican distancias de Manhattan. Si dos puntos, que son observaciones cuyas componentes son el número de variables del dataframe, la distancia entre ambos, en 2D, es el largo de la hipotenusa del triángulo rectángulo que formarían ambos puntos con respecto a un punto imaginario de referencia que forme un ángulo de 90° o $\frac{\pi}{2}$ radianes. Las distancias de Manhattan en lugar de tomar la hipotenusa como distancia, parten de la suma de la longitud de los catetos. Digamos que una persona A está en una esquina y la otra, B, está justo en la esquina opuesta en diagonal a la primera en la misma manzana. La persona A tendría que caminar dos cuadras en la misma manzana para poder encontrarse con B, por lo que en este ejemplo la distancia de Manhattan (asociar el distrito de Manhattan en Nueva York con las cuadras a recorrerse entre dos puntos) sería 2. Luego el cálculo de LOF contrinúa y aplica el promedio de las distancias de los puntos con sus puntos vecinos (puntos son observaciones), extrapolando análogamente el concepto de distancias de Manhattan a N dimensiones, logrando finalmente obtener la densidad local (por esto es **Local Outlier** Factor) de cada observación. En otras palabras, obtenemos qué observación tiene menos vecinos, como una persona (llámese C) que vive en un pequeño pueblo sin edificios, sólo casas, tendrá unos pocos vecinos, mientras que una persona D que vive en una ciudad muy poblada, con predominancia de edificios y alta densidad poblacional(como Manhattan) tendrá muchos más vecinos.

Como las variables están expresadas en unidades diferentes, primero las estandarizamos.
"""

!pip install scikit-learn #instalación de librería sklearn. Ofrece múltiples herramientas de machine learning y modelado estadístico.

from sklearn.preprocessing import StandardScaler #importación para estandarización de variables.
#Nótese que ahora sí es necesario estandarizar primero, porque LOF no considera escalas como lo hacía Mahalanobis.
from sklearn.neighbors import LocalOutlierFactor #importación para LOF.

#Préstese atención a que también se están estandarizando variables de polaridad y sentimiento debido a que pueden variar en una escala que incluye números negativos.
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df[cols_cuantitativas]) #Estandarización.

# n_neighbors: cantidad de vecinos que se usa para definir el entorno local
# contamination: proporción esperada de observaciones atípicas
lof = LocalOutlierFactor(n_neighbors=1000, contamination=0.05) # ajustamos el modelo. Consideramos 1000 vecinos y nos ponemos más rigurosos con una contaminación de 0.05
pred_lof = lof.fit_predict(X_scaled)

# sklearn entrega el score con signo negativo: lo cambiamos para que un valor mayor signifique una mayor anomalía
df['lof'] = -lof.negative_outlier_factor_
df['atipico_lof'] = pred_lof == -1

df[['id'] + cols_cuantitativas + ['lof', 'atipico_lof']] \
    .sort_values('lof', ascending=False).head(10)

"""###Isolation Forest:

Busca observaciones que pueden ser aisladas rápidamente mediante divisiones aleatorias.

Si una observación queda aislada con pocas divisiones, tiene mayor probabilidad de ser atípica.

En esta tabla usaremos un score transformado para que, igual que en los otros métodos, un valor mayor indique mayor anomalía, debido a que menor score implica un aislamiento más rápido de la observación y por esto se realiza la modificación, para poder hacer el resultado comparable con los otros dos.
"""

from sklearn.ensemble import IsolationForest

# n_estimators: cantidad de árboles del bosque
# contamination: proporción esperada de observaciones atípicas
iso = IsolationForest(n_estimators=200, contamination=0.05, random_state=42)
iso.fit(X_scaled)

# decision_function: valores más bajos indican mayor anomalía
df['isolation_forest'] = -iso.decision_function(X_scaled)
df['atipico_if'] = iso.predict(X_scaled) == -1

df[['id'] + cols_cuantitativas + ['isolation_forest', 'atipico_if']] \
    .sort_values('isolation_forest', ascending=False).head(10)

#A continuación una comparación entre los 3 métodos para ver cuáles fueron los resultados en común:
#Importación de matplotlib para gráficos
!pip install matplotlib
import matplotlib.pyplot as plt

#Tomaremos el top 10:

top10_m = set(df.nlargest(10, 'mahalanobis_2')['id'])
top10_lof = set(df.nlargest(10, 'lof')['id'])
top10_if = set(df.nlargest(10, 'isolation_forest')['id'])
ids = sorted(top10_m | top10_lof | top10_if)
frecuencia = [sum(i in grupo for grupo in [top10_m, top10_lof, top10_if]) for i in ids]

plt.figure(figsize=(17, 5))
plt.bar([str(i) for i in ids], frecuencia)
plt.xlabel('ID del ciclo')
plt.ylabel('Cantidad de métodos')
plt.title('Coincidencia entre los tres métodos: Top 10')
plt.yticks([1, 2, 3])
plt.show()

"""No hay coincidencias entre los 3 métodos para ninguno de los outliers clasificados por Mahalanobis, LOF y Isolation Forest. A su vez se observó que el retirar campos o quitar registros con valores atípicos no altera significativamente los coeficientes de correlación con respecto a la variable Shares. De momento, no se tratarán estos valores debido a que no hay pruebas concluyentes para hacerlo.
En todo caso, si un posterior análisis descriptivo o inferencial requiere de alguna medida respecto a dichos valores, se crearon variables anteriormente para poder evaluar dichos escenarios.

## 3. ANÁLISIS EXPLORATORIO Y DESCRIPTIVO

### 3.1 Estadísticos descriptivos
"""

# Resumen estadístico de las variables numéricas.
df.describe()

"""**Interpretación del grupo:** pendiente. Aquí se deberán comentar los principales valores observados en la tabla.

### 3.2 Análisis de la variable objetivo: `shares`
"""

# Resumen estadístico específico de la variable objetivo.
df['shares'].describe()

"""**Interpretación del grupo:** pendiente. Aquí se analizará la distribución general de `shares`, su dispersión y la posible presencia de valores extremos.

### 3.3 Distribución de las variables
**Pendiente de desarrollo.**

### 3.4 Análisis de relaciones entre variables
**Pendiente de desarrollo.**

### 3.5 Matriz de correlación
"""

# Calculamos la matriz de correlación entre las variables numéricas.
df.corr()

"""**Interpretación del grupo:** pendiente. Se deberán identificar las relaciones más relevantes y posibles problemas de colinealidad.

### 3.6 Principales hallazgos del análisis exploratorio
**Pendiente de desarrollo.**

## 4. DEFINICIÓN DEL PROBLEMA PREDICTIVO

### 4.1 Pregunta de investigación, objetivo y variable objetivo

¿En qué medida las características de un artículo publicado online permiten predecir su popularidad?

OBJETIVO Predecir la popularidad de una noticia, utilizando como medida
la cantidad de veces que fue compartida.

VARIABLE OBJETIVO (y) shares

Una empresa de contenidos digitales necesita conocer, antes de publicar o promocionar un artículo, qué características están asociadas con una mayor difusión en redes sociales. Un modelo predictivo permitiría estimar la popularidad esperada de un artículo y aportar información para optimizar decisiones sobre contenido, formato y publicación.

--------------------------------------------------------------------------

### 4.2 Necesidad que busca resolver el modelo

La necesidad de negocio ya se encuentra planteada en el apartado anterior y podrá ser revisada por el grupo antes de la entrega.

### 4.3 Hipótesis iniciales

**Pendiente de acordar por el grupo.** Las hipótesis deberán formularse antes del modelado para luego contrastarlas con los resultados.

## 5. MUESTREO E INFERENCIA

### 5.1 Extracción de la muestra aleatoria de n = 750
### 5.2 Comparación muestra vs. población
### 5.3 Media de `shares`
### 5.4 Varianza de `shares`
### 5.5 Evaluación de la representatividad de la muestra

**Sección pendiente de desarrollo.**

## 6. MODELO ESTADÍSTICO: REGRESIÓN LINEAL

### 6.1 Preparación de las variables
### 6.2 Regresión lineal con la muestra de 750
### 6.3 Análisis de coeficientes y significatividad
### 6.4 Regresión lineal con la base completa
### 6.5 Análisis de coeficientes y significatividad
### 6.6 Comparación muestra vs. base completa
### 6.7 Comparación del R² y errores estándar

**Sección pendiente de desarrollo.**

## 7. MACHINE LEARNING

### 7.1 Preparación de los datos
### 7.2 División Train/Test
### 7.3 Modelo de Machine Learning N.º 1
### 7.4 Modelo de Machine Learning N.º 2
### 7.5 Evaluación: MAE, MSE, RMSE y R²
### 7.6 Comparación de los modelos
### 7.7 Análisis de importancia de variables
### 7.8 Overfitting y optimización

**Sección pendiente de desarrollo.**

## 8. COMPARACIÓN: ESTADÍSTICA vs. MACHINE LEARNING

### 8.1 Capacidad explicativa de la Regresión Lineal
### 8.2 Capacidad predictiva de Machine Learning
### 8.3 Interpretabilidad vs. precisión
### 8.4 Selección del modelo para producción

**Sección pendiente de desarrollo.**

## 9. CONCLUSIONES

### 9.1 Principales hallazgos
### 9.2 Validación de las hipótesis iniciales
### 9.3 Limitaciones del análisis
### 9.4 Variables adicionales que mejorarían el modelo
### 9.5 Conclusión final

**Sección pendiente de desarrollo.**
"""